# Generated by Django 3.1.7 on 2021-03-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('st_username', models.CharField(max_length=25)),
                ('st_email', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('st_pass', models.CharField(max_length=25)),
                ('st_dob', models.DateField()),
                ('st_clgname', models.CharField(max_length=25)),
            ],
        ),
    ]
