# Generated by Django 3.1.7 on 2021-03-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eishel_student_app', '0003_teacher_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_details',
            fields=[
                ('ex_sub', models.CharField(max_length=25)),
                ('ex_name', models.CharField(max_length=25)),
                ('ex_date', models.DateField()),
                ('ex_time', models.TimeField()),
                ('ex_stu', models.IntegerField()),
                ('ex_marks', models.IntegerField()),
                ('ex_noq', models.IntegerField()),
                ('ex_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('ex_pass', models.CharField(max_length=25)),
            ],
        ),
    ]
