# Generated by Django 3.1.7 on 2021-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eishel_student_app', '0004_exam_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ex_details',
            fields=[
                ('ex_id', models.CharField(default='ex_dbms', max_length=25, primary_key=True, serialize=False)),
                ('ex_q', models.CharField(max_length=100)),
                ('ex_q_marks', models.IntegerField()),
            ],
        ),
    ]
