# Generated by Django 3.1.7 on 2021-03-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eishel_student_app', '0005_ex_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ex_details',
            name='ex_id',
        ),
        migrations.AddField(
            model_name='ex_details',
            name='exm_id',
            field=models.CharField(default='exam_dbms', max_length=25, primary_key=True, serialize=False),
        ),
    ]
