# Generated by Django 3.1.7 on 2021-03-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eishel_student_app', '0007_ans_stu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ans_key_details',
            fields=[
                ('examm_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('ex_q_no', models.IntegerField(default=1)),
                ('ans_key_main', models.TextField()),
                ('ans_key_A', models.TextField()),
                ('ans_key_B', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ans_stu',
            name='exam_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ex_details',
            name='exm_id',
            field=models.CharField(default='ex_dbms', max_length=25, primary_key=True, serialize=False),
        ),
    ]
