# Generated by Django 3.1.7 on 2021-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eishel_student_app', '0009_temp_ans_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_check_data',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('given_m', models.IntegerField(default=1)),
            ],
        ),
    ]
