# Generated by Django 3.1.7 on 2021-04-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eishel_student_app', '0010_temp_check_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_features',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feature_str', models.CharField(max_length=200)),
                ('prediction_int', models.IntegerField(default=1)),
            ],
        ),
    ]
